### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Harry-KIT** [csyanbin/3DStyleGAN-CT-backup#2]
Hi @csyanbin. Thank you for sharing this good repo.
I am trying to repeat this implementation. But it shows an error below. Could you recommend how to do it?

Local submit - run_dir: results/00003-3dstylegan2-SCT_tfrecord-4gpu-Gorig-Dorig-3d-1mm-base567
dnnlib: Running training.training_loop_3d.training_loop() on localhost...
2023-05-15 04:09:50.209031: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:tensorflow:From /home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
CUDA CASHE PATH
/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/tflib/_cudacache
2023-05-15 04:09:50.979121: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-15 04:09:50.983562: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-05-15 04:09:50.984283: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-05-15 04:09:51.745074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:18:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2023-05-15 04:09:51.746075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2023-05-15 04:09:51.747016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 2 with properties: 
pciBusID: 0000:5e:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2023-05-15 04:09:51.747948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 3 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2023-05-15 04:09:51.748902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 4 with properties: 
pciBusID: 0000:d8:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2023-05-15 04:09:51.748927: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-05-15 04:09:51.750981: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2023-05-15 04:09:51.751034: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2023-05-15 04:09:51.751698: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-05-15 04:09:51.751898: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-05-15 04:09:51.753038: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-05-15 04:09:51.753513: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2023-05-15 04:09:51.753623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2023-05-15 04:09:51.764092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1, 2, 3, 4
2023-05-15 04:09:51.764129: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-05-15 04:09:53.550416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-05-15 04:09:53.550449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 2 3 4 
2023-05-15 04:09:53.550455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y Y Y Y 
2023-05-15 04:09:53.550458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N Y Y Y 
2023-05-15 04:09:53.550461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 2:   Y Y N Y Y 
2023-05-15 04:09:53.550464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 3:   Y Y Y N Y 
2023-05-15 04:09:53.550467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 4:   Y Y Y Y N 
2023-05-15 04:09:53.557142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30125 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:18:00.0, compute capability: 7.0)
2023-05-15 04:09:53.559428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30125 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2023-05-15 04:09:53.561581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30125 MB memory) -> physical GPU (device: 2, name: Tesla V100-PCIE-32GB, pci bus id: 0000:5e:00.0, compute capability: 7.0)
2023-05-15 04:09:53.563767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30125 MB memory) -> physical GPU (device: 3, name: Tesla V100-PCIE-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0)
2023-05-15 04:09:53.565986: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 30125 MB memory) -> physical GPU (device: 4, name: Tesla V100-PCIE-32GB, pci bus id: 0000:d8:00.0, compute capability: 7.0)
Streaming data using training.dataset.TFRecordDataset...

max_shape
(1, 256, 256, 224)
base_size
[5, 6, 7]

self.resolution
204
resolution
None

(1, 8, 8, 7)
(1, 16, 16, 14)
(1, 32, 32, 28)
(1, 64, 64, 56)
(1, 128, 128, 112)
(1, 256, 256, 224)

 Dataset Repeated

 Dataset Repeated

 Dataset Repeated

 Dataset Repeated

 Dataset Repeated

 Dataset Repeated

Dataset shape = [1, 255, 306, 357]
Dynamic range = [0, 1.0]
Label size    = 0
Initialize data arrays
Random LayOut

2023-05-15 04:09:54.018059: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Traceback (most recent call last):
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable Dataset/labels_var from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/Dataset/labels_var/N10tensorflow3VarE does not exist.
	 [[{{node Dataset/normalize_element/ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_training_3d.py", line 860, in <module>
    main()
  File "run_training_3d.py", line 855, in main
    run(**vars(args))
  File "run_training_3d.py", line 784, in run
    dnnlib.submit_run(**kwargs)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/training_loop_3d.py", line 154, in training_loop
    grid_size, grid_reals, grid_labels = misc.setup_snapshot_image_grid(training_set, **grid_args)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/misc.py", line 239, in setup_snapshot_image_grid
    reals[:], labels[:] = training_set.get_minibatch_np(gw * gh)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/dataset.py", line 220, in get_minibatch_np
    self.configure(minibatch_size, lod)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/dataset.py", line 210, in configure
    self._tf_init_ops[lod].run({self._tf_minibatch_in: minibatch_size})
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2596, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 5547, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable Dataset/labels_var from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/Dataset/labels_var/N10tensorflow3VarE does not exist.
	 [[node Dataset/normalize_element/ReadVariableOp (defined at /data2/gayrat/vs-projects/3DStyleGAN-CT/training/dataset.py:171) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Dataset/normalize_element/ReadVariableOp:
 Dataset/labels_var (defined at /data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/tflib/tfutil.py:257)

Original stack trace for 'Dataset/normalize_element/ReadVariableOp':
  File "run_training_3d.py", line 860, in <module>
    main()
  File "run_training_3d.py", line 855, in main
    run(**vars(args))
  File "run_training_3d.py", line 784, in run
    dnnlib.submit_run(**kwargs)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/training_loop_3d.py", line 151, in training_loop
    training_set = dataset.load_3d_dataset(data_dir=dnnlib.convert_path(data_dir), verbose=True, **dataset_args)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/dataset.py", line 299, in load_3d_dataset
    dataset = dnnlib.util.get_obj_by_name(class_name)(**kwargs)
  File "/data2/gayrat/vs-projects/3DStyleGAN-CT/training/dataset.py", line 171, in __init__
    self._tf_labels_dataset = tf.data.Dataset.from_tensor_slices(self._tf_labels_var)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2537, in from_tensor_slices
    return DatasetV1Adapter(DatasetV2.from_tensor_slices(tensors))
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 691, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3155, in __init__
    element = structure.normalize_element(element)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 111, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1992, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1393, in _dense_var_to_tensor
    return self.value()
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 565, in value
    return self._read_variable_op()
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 672, in _read_variable_op
    result = read_and_set_handle()
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 662, in read_and_set_handle
    result = gen_resource_variable_ops.read_variable_op(
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 484, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "/home/gayrat/miniconda3/envs/3dgan_backup/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by Harry-KIT** [comment]
Maybe the problem with the dataset. I don't know. I used dicom image dataset. Then png dataset. But the same error

**Comment by Harry-KIT** [comment]
![image](https://github.com/csyanbin/3DStyleGAN-CT-backup/assets/57295863/2241eef9-7968-4a82-9442-301db1097d64)
